tasks:
  generateGitProperties:
    action: !org.amper.gitcommitid.generateGitProperties
      propertiesFile: ${taskOutputDir}/${pluginSettings.propertiesFile}
      settings: ${pluginSettings}
    markOutputsAs:
      - path: ${action.propertiesFile}
        kind: jvm-resources
